name: Python Greet Workflow

on:
  push:
    branches: ["**"]  # Triggers on push to any branch
  pull_request:
    branches: [main]  # Triggers on PR targeting main

jobs:
  greet-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run Hello.py
        run: |
          python Hello.py
